export const ProdActions = {
  SET_FETCHED_DATA: "SET_FETCHED_DATA",
  SET_SINGLE_DATA: "SET_SINGLE_DATA",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_CART: "UPDATE_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};
